# Generated by Django 2.1.5 on 2019-02-12 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser_name', models.CharField(max_length=200)),
                ('item_description', models.CharField(max_length=200)),
                ('item_price', models.FloatField(max_length=200)),
                ('purchase_count', models.IntegerField(default=1)),
                ('merchant_address', models.CharField(max_length=200)),
                ('merchant_name', models.CharField(max_length=200)),
            ],
        ),
    ]
